# Generated by Django 3.0.8 on 2020-09-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Processors', 'Processors'), ('Motherboards', 'Motherboards'), ('Memory(ram)', 'Memory(ram)'), ('Storage', 'Storage'), ('Cabinets', 'Cabinets'), ('Cooling System', 'Cooling System'), ('Accessories', 'Accessories')], max_length=200, null=True),
        ),
    ]
